hoplax.autocompletes.mdc = [
{ url: "https://developer.mozilla.org/en/JavaScript/Guide/Working_with_Objects#Creating_New_Objects", topic: " created by the user script" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/About#Formatting_conventions", topic: "Formatting conventions" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/About#JavaScript_history", topic: "JavaScript history" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/About", topic: "About this Reference" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/About#What_you_should_already_know", topic: "What you should already know" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/About#Where_to_find_JavaScript_information", topic: "Where to find JavaScript information" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Comments/comment", topic: "Code comments" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Deprecated_Features", topic: "Appendix B - Deprecated Features" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Functions_and_function_scope/arguments", topic: "arguments" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Functions_and_function_scope", topic: "Functions and function scope" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Array", topic: "Array" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Boolean", topic: "Boolean" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date", topic: "Date" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/decodeURIComponent", topic: "decodeURIComponent" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/decodeURI", topic: "decodeURI" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/encodeURIComponent", topic: "encodeURIComponent" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/encodeURI", topic: "encodeURI" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Error", topic: "Error" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/EvalError", topic: "EvalError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/eval", topic: "eval" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Function", topic: "Function" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Infinity", topic: "Infinity" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/isFinite", topic: "isFinite" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/isNaN", topic: "isNaN" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Math", topic: "Math" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/NaN", topic: "NaN" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Number", topic: "Number" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Object", topic: "Object" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/parseFloat", topic: "parseFloat" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/parseInt", topic: "parseInt" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/RangeError", topic: "RangeError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/ReferenceError", topic: "ReferenceError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/RegExp", topic: "RegExp" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/String", topic: "String" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/SyntaxError", topic: "SyntaxError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects", topic: "Global Objects" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/TypeError", topic: "TypeError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/undefined", topic: "undefined" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/URIError", topic: "URIError" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Arithmetic_Operators", topic: "Arithmetic Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Assignment_Operators", topic: "Assignment Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Bitwise_Operators", topic: "Bitwise Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Comparison_Operators", topic: "Comparison Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Logical_Operators", topic: "Logical Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Member_Operators", topic: "Member Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Operator_Precedence", topic: "Operator Precedence" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/Comma_Operator", topic: "Comma Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/Conditional_Operator", topic: "Conditional Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/delete", topic: "delete Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/function", topic: "function Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/get", topic: "get Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/instanceof", topic: "instanceof Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/in", topic: "in Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/new", topic: "new Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special_Operators/let_Operator", topic: "let Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special_Operators/yield_Operator", topic: "yield Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/set", topic: "set Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/this", topic: "this Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/typeof", topic: "typeof Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/void", topic: "void Operator" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators/String_Operators", topic: "String Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Operators", topic: "Operators" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Reserved_Words", topic: "Appendix A - Reserved Words" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/block", topic: "block" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/break", topic: "break" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/const", topic: "const" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/continue", topic: "continue" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/debugger", topic: "debugger" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/do...while", topic: "do...while" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/export", topic: "export" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/for_each...in", topic: "for each...in" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/for...in", topic: "for...in" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/for", topic: "for" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/function", topic: "function" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/if...else", topic: "if...else" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/import", topic: "import" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/label", topic: "label" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/let", topic: "let" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/return", topic: "return" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/switch", topic: "switch" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/throw", topic: "throw" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements", topic: "Statements" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/try...catch", topic: "try...catch" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/var", topic: "var" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/while", topic: "while" },
{ url: "https://developer.mozilla.org/en/JavaScript/Reference/Statements/with", topic: "with" },
{ url: "https://developer.mozilla.org/en/JavaScript", topic: "JavaScript" },
];
